import React from 'react'
import { FaHtml5 } from "react-icons/fa";
import { CiSettings } from "react-icons/ci";

function CodeWriter({lang,logo}) {
  return (
  <div className="w-full min-h-96 h-full flex flex-col">
  <div className="sticky top-0 z-10 bg-black">
    <div className="h-6 flex items-center justify-between pr-4">
      <div className="flex items-center gap-1 justify-start px-1 opacity-80 cursor-pointer">
        {logo}
        <span className="text-white w-2/12">{lang}</span>
      </div>
      <div>
        <CiSettings className="text-white cursor-pointer bg-gray-700 rounded-sm" />
      </div>
    </div>
  </div>
  
  <div className="overflow-auto flex-grow">
  Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...

Lorem ipsum dolor sit amet, consectetuer adipiscing elit...


  </div>
</div>


  )
}

export default CodeWriter